[project]
name = "Probabilistic_Models"
version = "1.0.1"
description = "I'm trying to implement most of the probabilistic models from scratch."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.9",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "requests>=2.34.2",
    "scipy>=1.18.0",
    "seaborn>=0.13.2",
]
